### ISSUE TITLE
Any way to define public assets on this setup ?

### ISSUE THREAD

**Issue by ranjitatwal30** [Shopify/shopify-demo-app-node-react#64] opened 2019-11-04 19:16 UTC
# Bug summary

Tried koa as well next.js tuts, cannot seem to setup public path to serve my assets.

Tried naming folders as:

1. static

2. public 

But no luck so far !

**Comment by katiedavis** [comment] 2019-11-04 19:24
Hi @ranjitatwal30! 
Here's some links to help you out:
https://github.com/zeit/next.js/tree/master#static-file-serving-eg-images
The next.js forums can be helpful too:
https://spectrum.chat/next-js?tab=posts

As this is not a bug related to our tutorial content I'm going to close this issue.

**Closed by katiedavis** 2019-11-04 19:24 UTC

**Comment by ranjitatwal30** [comment] 2019-11-04 19:33
Well, figured it out. I created "static" folder which is served as "/static".

**Note:** for some reason "public" served  as "/" did not work for me
