### ISSUE TITLE
Error {name: "AppBridgeError", message: "APP::ERROR::INVALID_CONFIG: apiKey must be provided", action: undefined, type: "APP::ERROR::INVALID_CONFIG", stack: "AppBridgeError: APP::ERROR::INVALID_CONFIG: apiKey must be provided"}

### ISSUE THREAD

**Issue by Popesites** [Shopify/shopify-demo-app-node-react#38] opened 2019-07-23 19:53 UTC
# Bug summary

Okay, so I'm trying to work with the Provider and get the API_KEY from the next.config.js file export. However, It's not being exported properly. When I try to run the app from within the branch fetch-data-with-apollo-starter-files, I get a looping error message in my console 

```Error {name: "AppBridgeError", message: "APP::ERROR::INVALID_CONFIG: apiKey must be provided", action: undefined, type: "APP::ERROR::INVALID_CONFIG", stack: "AppBridgeError: APP::ERROR::INVALID_CONFIG: apiKey must be provided"}```

<img width="1433" alt="Screen Shot 2019-07-23 at 12 52 13 PM" src="https://user-images.githubusercontent.com/17707366/61742776-b6f0dd80-ad48-11e9-9c9a-94951d7e0b65.png">

When I replace the API_KEY constant with the actual API key in string format, the app loads properly.

## Steps to reproduce the problem

1. Install fetch-data-with-apollo-starter-files
2. Run in production mode with browser console open
3. See error

**Comment by katiedavis** [comment] 2019-07-23 19:55
Hi @Popesites what format do you have the key in your `.env` file? I just pulled that branch and ran it and it console logs the correct key from both the config and `_app.js` file

**Comment by katiedavis** [comment] 2019-07-23 19:56
You may have to set this variable differently if you're building for production and deploying. This config set up was for local development and has not been tested for production.

**Comment by Popesites** [comment] 2019-07-23 19:59
@katiedavis Can you show an example of how the .env file should be formatted? 

I am able to console.log() the process.env.SHOPIFY_API_KEY from _app.js as well as next.config.js and get a valid API key, but when I console.log(API_KEY) from the _app.js file, it is undefined.

**Comment by katiedavis** [comment] 2019-07-23 20:02
@Popesites 🤔
SHOPIFY_API_KEY=STRING HERE
SHOPIFY_API_SECRET_KEY=STRING HERE
TUNNEL_URL=TUNNEL URL
API_VERSION='2019-04'

Did you make any changes to the `fetch-data-with-apollo-starter-files` locally? Have you pulled the the most recent version? Are you running `npm run dev`?

**Comment by Popesites** [comment] 2019-07-23 20:04
The only thing that I changed from the branch is adding: 
NODE_ENV="production"

Everything else is formatted the same as your example provided. Also when NODE_ENV is not set to production, I am able to get a value for API_KEY, but when NODE_ENV is set to production, the API_KEY is returning undefined in _app.js.

**Comment by katiedavis** [comment] 2019-07-23 20:10
I think you're going to have to take this question to the next.js forums:
https://spectrum.chat/zeit?tab=posts

I can take a look tomorrow, but this is outside of what we set up for this tutorial and I don't want to leave you hanging for too long. I'm going to close this issue for now, as it's not a bug related to our content and I'll ping you on this issue if I come up with anything!

**Closed by katiedavis** 2019-07-23 20:10 UTC

**Comment by mrfoster** [comment] 2019-08-20 15:54
I am getting the same error with a new app created using the shopify cli. It is not working for my production server but works locally. I don't suppose anyone got to the bottom of it?

**Comment by mrfoster** [comment] 2019-08-21 08:55
It's now working for me. I realised that the SHOPIFY_API_KEY needs to be present when performing a build.  I had assumed it was just a runtime setting and hadn't included it on build server.
